const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

module.exports = {
  "SESSION_ID": process.env.SESSION_ID || "Byte;;;eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiWUxWMDNYbmxuNFBLMlZVK2ljUnBjTy9MakNvaHp3Q3BOOGtEQ0ZvQlZtZz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiT256Nk5EcjBPMlEyb2YyWU1EdjBBcGJhYWxUZE9udzRIejE0MnArMUpTST0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJjQ2RTVktkbHRPL2tSejdsZUNyMnBnc05Ud29qNGVwczBuVDhQYnhDS2tRPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJsNzdrNHI1QXFqdllPTG9ZZ1ZaUlowUE5GMWNtODl1SWFqbFY5MkdMc1JFPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImtQQVJpaHBBRS9SMlBGZ1lrVEpDU3NURlNWZW1vUjJYYXA0bzBBT0dYSGs9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InVZK3FJVC9GbUFnZFROY214ajluVEtCOGtCT25QMzkzTHQ2NzF1Uis3U009In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoicU9uMmw1MWxFQVMzSUtBV2tmYSs2SjNFeXVaSGQ2MWhhOWxHdjFscWJIYz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiYXpROExqaWFqYWl1Rnd5cGtrd3NWbGNhMGxmS3R3d0dxeWdpKzZnaEltVT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkIyclExMUNJVUJjbGxNVUQ0NERUajVHaG95VTZpTC9LakV3eWNBbE5VdWZWUTBVSGwzZzFuN3hzN0FXRUxHOUliWkI2WlNtT2dwWFh4QUpRa1NiZ0RnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6NjgsImFkdlNlY3JldEtleSI6IjdzTTdWZStGc1l3VlFSOFFiaGJsTkFuekUzRmpOZGJNV1BUVjZuM1hrSFU9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbeyJrZXkiOnsicmVtb3RlSmlkIjoiOTIzMjc3NzY5Nzg4QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IkNDMjJEOUEzNDEzRjlDOERFMDE3MjhENEVFNkZCOUE5In0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NDMwNDgwODZ9LHsia2V5Ijp7InJlbW90ZUppZCI6IjkyMzI3Nzc2OTc4OEBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiI3NjYyQTM0QTdBQjYzODNEQUJEMkExOERGNjlDQzdDRiJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzQzMDQ4MDg2fV0sIm5leHRQcmVLZXlJZCI6NDIsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjo0MiwiYWNjb3VudFN5bmNDb3VudGVyIjoxLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJSOGtGLWFjaFJ1Q3IyZTJtbFRGLVRRIiwicGhvbmVJZCI6Ijk0ODYwYjVkLWE3ZjEtNDlmYi1iZGIyLTQ2Nzc2Mjk0NGY2YSIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJRSlNkZDAzU3pwblNZaDFhSXVNNFFYcFh2R2c9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMWxvazdSeDBlcmdycWhYTjNkV3ZLeW1GN2VnPSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IkhXMk5aUEs2IiwibWUiOnsiaWQiOiI5MjMyNzc3Njk3ODg6NjFAcy53aGF0c2FwcC5uZXQiLCJuYW1lIjoi2KjZhtiv24Eg2LnYtNmCINi02K/bjCDinaTvuI/igI3wn6m5In0sImFjY291bnQiOnsiZGV0YWlscyI6IkNNaUt5dThIRUlHYms3OEdHQUVnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJBZzJQa3ZQUDgvWndxS2hCbkN0M0NJVFNIcnRZekJLVkNYRzhVT1Z1SWhzPSIsImFjY291bnRTaWduYXR1cmUiOiJtYWhBaFhsVW9oUmFzcDI1bnZPbUxPc2lXdmgvcTZ3RVptd0FMU25YWEpyd1pBNUNqcGNFVGduWCtERmtlL3VoZXMvR21rdXBqVFhkMjVEdWZHdkFDQT09IiwiZGV2aWNlU2lnbmF0dXJlIjoic3QyV2xRVC9SSEJqSEJYdGNvREQyam1WNEVMSVhoNXFOVTg0TmVqeE1QS1ZnVzVhTlRnWGlXcnhxaE5uU1FRNkloMkgreGVNMFNEekV1K1ZnQXJ6QUE9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiI5MjMyNzc3Njk3ODg6NjFAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCUUlOajVMenovUDJjS2lvUVp3cmR3aUUwaDY3V013U2xRbHh2RkRsYmlJYiJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTc0MzA0ODA3OCwibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFGWWkifQ==",
  "ALIVE_IMG": process.env.ALIVE_IMG || "https://raw.githubusercontent.com/HyHamza/HyHamza/refs/heads/main/Images/logo.jpg",
  "PREFIX": process.env.PREFIX || ".",
  "AUTO_READ_STATUS": process.env.AUTO_READ_STATUS === 'true',
  "MODE": process.env.MODE || "public",
  "OWNER_NUMBER": process.env.OWNER_NUMBER || "923072380380",
  "OWNER_NAME": process.env.OWNER_NAME || "Hamza",
  "ALWAYS_ONLINE": process.env.ALWAYS_ONLINE === 'true',
  "PRESENCE": process.env.PRESENCE || "online",
  "OMDB_API_KEY": process.env.OMDB_API_KEY || "76cb7f39",
  "READ_CMD": process.env.READ_CMD === 'true',
  "AUTO_VOICE": process.env.AUTO_VOICE === 'true',
  "AUTO_STICKER": process.env.AUTO_STICKER === 'true',
  "AUTO_REPLY": process.env.AUTO_REPLY === 'true',
  "AUTO_REACT": process.env.AUTO_REACT === 'true',
  "WELCOME": process.env.WELCOME === 'true',
  "ANTI_BAD": process.env.ANTI_BAD === 'true',
  "ANTI_LINK": process.env.ANTI_LINK === 'true',
  "ANTI_GROUP_LINK": process.env.ANTI_GROUP_LINK === 'true',
  "ANTI_DELETE": process.env.ANTI_DELETE === 'true',
  "ANTI_VIEW_ONCE": process.env.ANTI_VIEW_ONCE === 'true',
  "ANTI_BOT": process.env.ANTI_BOT === 'true',
  "PREMIUM_USERS": process.env.PREMIUM_USERS || "",
  "COUNTRY_BLOCK": process.env.COUNTRY_BLOCK === 'true',
  "COUNTRY_BLOCK_CODE": process.env.COUNTRY_BLOCK_CODE || "972",
  "EMOJI": process.env.EMOJI || "🙄",
  "AUTO_TYPING": process.env.AUTO_TYPING === 'true'
};
